server:
  port: 8080  #  配置启动端口号

mybatis:
  config-location: classpath:mybatis-config.xml    #  mybatis主配置文件所在路径
  type-aliases-package: com.example.project*  #  定义所有操作类的别名所在包
  mapper-locations: classpath:mapper/*.xml     #  所有的mapper映射文件

spring: #springboot的配置
  datasource: #定义数据源
    #3306是mysql的端口号。serverTimezone是定义时区，照抄就好，mysql高版本需要定义这些东西
    #useSSL也是某些高版本mysql需要问有没有用SSL连接
    url: jdbc:mysql://43.143.45.157:3306/test?serverTimezone=GMT%2B8&useSSL=FALSE
    username: root  #数据库用户名，root为管理员
    password: zhuhualiang123! #该数据库用户的密码
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    host: 43.143.45.157
    database: 0
    password: zhuhualiang123!

# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath:mapper/*.xml
  # 以下配置均有默认值,可以不设置
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl